/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import static javaapplication1.Clinic.clinic_tabl;
import static javaapplication1.Clinic.disease;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
        
        functions.det_loading();
        functions.combo_loading();
        
        DefaultTableModel mod = (DefaultTableModel)Clinic.clinic_tabl.getModel();
        
        save.setVisible(false);
        saved.setVisible(false);
        reset.setVisible(false);
        close.setVisible(false);
        min.setVisible(false);
        
        name1.setBackground(new Color(255,255,255,50));
        age1.setBackground(new Color(255,255,255,50));
        phone1.setBackground(new Color(255,255,255,50));
        disease1.setBackground(new Color(255,255,255,50));
        date2.setBackground(new Color(255,255,255,50));
        spe_disease1.setBackground(new Color(255,255,255,50));
        cure.setBackground(new Color(255,255,255,50));
        rec.setBackground(new Color(255,255,255,50));
        date1.setBackground(new Color(255,255,255,50));
        address1.setBackground(new Color(255,255,255,50));
        id1.setBackground(new Color(255,255,255,50));
        
        
        name1.setText(Clinic.name.getText());
        age1.setText(Clinic.age.getText());
        phone1.setText(Clinic.phone.getText());
        id1.setText(mod.getValueAt(Clinic.clinic_tabl.getSelectedRow(),0).toString());
        disease1.setSelectedItem(Clinic.disease.getSelectedItem());
        
        if(Clinic.disease.getSelectedItem() == "Eyes"){
            cure.setText("lorem eyes cure\n"
                + "lorem eyes cure\n"
                + "lorem eyes cure");
        }
        
        else if(Clinic.disease.getSelectedItem() == "Bones"){
            cure.setText("lorem bones cure\n"
                + "lorem bones cure\n"
                + "lorem bones cure\n");
        }
        
        else if(Clinic.disease.getSelectedItem() == "stomach"){
            cure.setText("lorem stomach cure\n"
                + "lorem stomach cure\n"
                + "lorem stomach cure");
        }
        
        else if(Clinic.disease.getSelectedItem() == "kindey"){
            cure.setText("lorem bones cure"
                + "lorem kindy cure\n"
                + "lorem kindey cure");
        }
        
        rec.setText("doctor recommendation\n"
                + "don't bla bla\n"
                + "don't bla bla\n"
                + "do bla bla");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        age1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        address = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        rec = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cure = new javax.swing.JTextArea();
        save = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        disease1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        spe_disease1 = new javax.swing.JTextField();
        cmb_disease = new javax.swing.JComboBox<>();
        saved = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 239, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 50));

        age1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        age1.setForeground(new java.awt.Color(255, 255, 255));
        age1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age1KeyReleased(evt);
            }
        });
        getContentPane().add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 50));

        phone1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 255, 255));
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });
        phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phone1KeyReleased(evt);
            }
        });
        getContentPane().add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Next visit date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 170, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("date of examination");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 210, 50));

        date2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date2.setForeground(new java.awt.Color(255, 255, 255));
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });
        getContentPane().add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 250, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("cure");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 90, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Doctors note");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 210, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("save");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 90, 50));

        name1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 250, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1130, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 550, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 580, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 550, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 550, 20));

        address.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 122, 80, 330));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 580, 20));

        rec.setEditable(false);
        rec.setColumns(20);
        rec.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        rec.setForeground(new java.awt.Color(51, 51, 51));
        rec.setLineWrap(true);
        rec.setRows(3);
        rec.setTabSize(5);
        rec.setWrapStyleWord(true);
        jScrollPane1.setViewportView(rec);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 250, 160));

        cure.setEditable(false);
        cure.setColumns(20);
        cure.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        cure.setForeground(new java.awt.Color(51, 51, 51));
        cure.setLineWrap(true);
        cure.setRows(3);
        cure.setTabSize(5);
        cure.setWrapStyleWord(true);
        jScrollPane2.setViewportView(cure);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 240, 150));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-50 (3).png"))); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveMouseReleased(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 50, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-50 (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 60, 40));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-left-rotation-55 (1).png"))); // NOI18N
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 60, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-left-rotation-55.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 70, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("reset");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, 90, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-page-50.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-subtract-35 (5).png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 40, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-subtract-35 (4).png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 40, 50));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 40, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-35.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 40, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("disease");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 90, 50));

        date1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 250, 40));

        disease1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        disease1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eyes", "Bones", "Ear, Nose and Throat", "stomach", "Dental", "Neurologists", "kindey", "Venereal", " ", " " }));
        disease1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disease1ActionPerformed(evt);
            }
        });
        getContentPane().add(disease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 250, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("address");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, 30));

        address1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address1.setForeground(new java.awt.Color(255, 255, 255));
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        getContentPane().add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 250, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ID");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 90, 50));

        id1.setEditable(false);
        id1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id1.setForeground(new java.awt.Color(255, 255, 255));
        id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id1KeyReleased(evt);
            }
        });
        getContentPane().add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 40, 30));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1140, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("specific disease");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 190, 40));

        spe_disease1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spe_disease1.setForeground(new java.awt.Color(255, 255, 255));
        spe_disease1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spe_disease1ActionPerformed(evt);
            }
        });
        getContentPane().add(spe_disease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 190, 40));

        cmb_disease.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(cmb_disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 180, 40));

        saved.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        saved.setForeground(new java.awt.Color(255, 255, 255));
        saved.setText("saved");
        getContentPane().add(saved, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details_2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save(){
        DefaultTableModel mod = (DefaultTableModel)Clinic.clinic_tabl.getModel() ;
        mod.setValueAt(details.name1.getText(), clinic_tabl.getSelectedRow(), 0);
        mod.setValueAt(details.age1.getText(), clinic_tabl.getSelectedRow(), 1);
        mod.setValueAt(details.phone1.getText(), clinic_tabl.getSelectedRow(), 2);
        mod.setValueAt(details.id1.getText(), clinic_tabl.getSelectedRow(), 3);
        mod.setValueAt(details.disease1.getSelectedItem(), clinic_tabl.getSelectedRow(), 4);
        
    }
    
    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2ActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void disease1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disease1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disease1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.setState(details.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        new Clinic().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        save();
        functions.saving();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        name1.setText(Clinic.name.getText());
        age1.setText(Clinic.age.getText());
        phone1.setText(Clinic.phone.getText());
        disease1.setSelectedItem(Clinic.disease.getSelectedItem());
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        functions.det_saving();
        functions.det_update();
        saved.setVisible(true);
    }//GEN-LAST:event_saveMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        name1.setText(Clinic.name.getText());
        age1.setText(Clinic.age.getText());
        phone1.setText(Clinic.phone.getText());
        disease1.setSelectedItem(Clinic.disease.getSelectedItem());
    }//GEN-LAST:event_resetMouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        save.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        reset.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
        save.setVisible(false);
    }//GEN-LAST:event_saveMouseExited

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
        // TODO add your handling code here:
        reset.setVisible(false);
    }//GEN-LAST:event_resetMouseExited

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private void age1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age1KeyReleased
        // TODO add your handling code here:
        functions.error_number(age1);
    }//GEN-LAST:event_age1KeyReleased

    private void phone1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone1KeyReleased
        // TODO add your handling code here:
        functions.error_number(phone1);
    }//GEN-LAST:event_phone1KeyReleased

    private void id1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id1KeyReleased
        // TODO add your handling code here:
        functions.error_number(id1);
    }//GEN-LAST:event_id1KeyReleased

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setVisible(false);
    }//GEN-LAST:event_closeMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        close.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(details.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        min.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        min.setVisible(false);
    }//GEN-LAST:event_minMouseExited

    private void spe_disease1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spe_disease1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spe_disease1ActionPerformed

    private void saveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseReleased
        // TODO add your handling code here:
        saved.setVisible(false);
    }//GEN-LAST:event_saveMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator address;
    public static javax.swing.JTextField address1;
    public static javax.swing.JTextField age1;
    private javax.swing.JLabel close;
    public static javax.swing.JComboBox<String> cmb_disease;
    private javax.swing.JTextArea cure;
    public static javax.swing.JTextField date1;
    public static javax.swing.JTextField date2;
    public static javax.swing.JComboBox<String> disease1;
    public static javax.swing.JTextField id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel min;
    public static javax.swing.JTextField name1;
    public static javax.swing.JTextField phone1;
    private javax.swing.JTextArea rec;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel save;
    private javax.swing.JLabel saved;
    public static javax.swing.JTextField spe_disease1;
    // End of variables declaration//GEN-END:variables
}
