/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.functions.loading;
import static javaapplication1.pharmacy.load;
import static javaapplication1.pharmacy.ph_table;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class pharmacy_sell extends javax.swing.JFrame {

    /**
     * Creates new form pharmacy_sell
     */
    public pharmacy_sell() throws ParseException {
        initComponents();
        
        transaction.getColumnModel().getColumn(0).setMinWidth(0);
        transaction.getColumnModel().getColumn(0).setMaxWidth(0);
        
        new_emp.setVisible(false);
        close.setVisible(false);
        min.setVisible(false);
        home.setVisible(false);
        add.setVisible(false);
        done.setVisible(false);
        sell.setVisible(false);
        delete.setVisible(false);
        
        name.setBackground(new Color (255,255,255,50));
        quantity.setBackground(new Color (255,255,255,50));
        price.setBackground(new Color (255,255,255,50));
        dt.setBackground(new Color (255,255,255,50));
        tm.setBackground(new Color (255,255,255,50));
        
        items.setOpaque(false);
        transaction.setOpaque(false);
        sc.setOpaque(false);
        sc1.setOpaque(false);
        sc.getViewport().setOpaque(false);
        sc1.getViewport().setOpaque(false);
        
       
        
        DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
        
        
        cr.setForeground(new Color (0,0,153));
        cr.setOpaque(false);
        
                
        
        for(int i = 0 ; i < 3 ; i++){
            
            items.getColumnModel().getColumn(i).setCellRenderer(cr);
            
        }
        
        for(int i = 0 ; i < 6 ; i++){
            
            transaction.getColumnModel().getColumn(i).setCellRenderer(cr);
            
        }
        
        Date day=Date.valueOf(LocalDate.now());
        Time time=Time.valueOf(LocalTime.now());
        java.util.Date ftime = new SimpleDateFormat("HH:mm:ss").parse(time.toString());
            String finaltime = new SimpleDateFormat("H:mm").format(ftime);
            String finalday = new SimpleDateFormat("d/M/yyyy").format(day);
            
        dt.setText(finalday);
        tm.setText(finaltime);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        min = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        name_ft = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        new_emp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cmp_emp = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dt = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sc = new javax.swing.JScrollPane();
        items = new javax.swing.JTable();
        sc1 = new javax.swing.JScrollPane();
        transaction = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        done = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-subtract-38.png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 40, 30));

        min1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-subtract-38 (1).png"))); // NOI18N
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min1MouseEntered(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 50, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-38 (1).png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 40, 40));

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-38.png"))); // NOI18N
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close1MouseEntered(evt);
            }
        });
        getContentPane().add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 40, 40));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-40 (1).png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 60, 90));

        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-40.png"))); // NOI18N
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
        });
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 50));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.setEnabled(false);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 80, 50));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("submit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 450, -1, 40));

        quantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityKeyReleased(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, 40));

        name_ft.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_ft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_ftActionPerformed(evt);
            }
        });
        getContentPane().add(name_ft, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 200, 50));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        tm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tm.setEnabled(false);
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 140, 60));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("employee");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 40));

        new_emp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_empActionPerformed(evt);
            }
        });
        getContentPane().add(new_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 160, 50));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("customer name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, 40));

        cname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 290, 50));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("customer phone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, 40));

        cphone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cphoneActionPerformed(evt);
            }
        });
        getContentPane().add(cphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 290, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 20, 290));

        cmp_emp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmp_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "venom", "alora", "jogeto", "dappo", "add new employee" }));
        cmp_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp_empActionPerformed(evt);
            }
        });
        getContentPane().add(cmp_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 200, 50));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("time");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 60, 50));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 40));

        dt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dt.setEnabled(false);
        dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtActionPerformed(evt);
            }
        });
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 50));

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 190, 50));

        items.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "quantity", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sc.setViewportView(items);

        getContentPane().add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 530, 230));

        transaction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idtrans", "employee", "customer", "customer phone", "date", "time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sc1.setViewportView(transaction);

        getContentPane().add(sc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 520, 730, 230));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("sell");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 40));

        jLabel15.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("delete");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, 50));

        jLabel16.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("add to basket");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 50));

        sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-sell-40 (1).png"))); // NOI18N
        sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellMouseExited(evt);
            }
        });
        getContentPane().add(sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-sell-40.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 40, 40));

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-done-40 (1).png"))); // NOI18N
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneMouseExited(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 390, 50, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-done-40.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 400, 40, 40));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-43 (1).png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 40, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-43.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 50, 50));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-shopping-basket-add-40.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 40, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-shopping-basket-add-40 (1).png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy_sell.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void cmp_name_loading(){
        
        String url ="jdbc:mysql://localhost:3306/Project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="select * from pharmacy_purchase where name like'"+name.getText()+"%';";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                name_ft.addItem(rs.getString("name"));
            }
            
            
            
            //System.out.print("load done");
            
            
            
        }
        catch(SQLException ex){
            
        }
        
    }
    
    public void load_trans(){
        
        String url ="jdbc:mysql://localhost:3306/Project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="select * from transaction order by idtransaction desc limit 1;";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel mod = (DefaultTableModel)transaction.getModel();
            
            while(rs.next()){
                
                mod.addRow(new Object[]{rs.getInt("idtransaction"),rs.getString("emp"),rs.getString("cname"),rs.getString("cphone"),rs.getString("date"),rs.getString("time")});
                
            }
            
            //System.out.print("load done");
            
            
            
        }
        catch(SQLException ex){
            
        }
        
    }
    
    public void load_items(){
        
        DefaultTableModel mod1 = (DefaultTableModel)transaction.getModel();
        String url ="jdbc:mysql://localhost:3306/Project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="select * from items where iditems ='"+mod1.getValueAt(0, 0)+"';";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel mod = (DefaultTableModel)items.getModel();
            
            while(rs.next()){
                
                mod.addRow(new Object[]{rs.getString("name"),rs.getInt("quantity"),rs.getDouble("price")});
                
            }
            
            //System.out.print("load done");
            
            
            
        }
        catch(SQLException ex){
            
        }
        
    }
    
    
    public void save_items(){
        
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="insert into items(  iditems, name, quantity, price) values(?,?,?,?);";
        
        
        String update = "update pharmacy_purchase set qty = qty - '"+quantity.getText()+"' where name = '"+name_ft.getSelectedItem().toString()+"' ;";
        
        DefaultTableModel mod = (DefaultTableModel)items.getModel();
        DefaultTableModel mod1 = (DefaultTableModel)transaction.getModel();
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            
            PreparedStatement ps = con.prepareStatement(sql) ;
            
            ps.setInt(1,Integer.parseInt(mod1.getValueAt(0, 0).toString()) );
            ps.setString(2, name_ft.getSelectedItem().toString());
            ps.setInt(3, Integer.parseInt(quantity.getText()));
            
            ps.setDouble(4, Double.parseDouble(price.getText()));
            
            ps.execute();
            
            st.execute(update);
            mod.setRowCount(0);
            load_items();
            
            //System.out.print("save done");
        }catch(SQLException ex){
            
        }
    }
    
    public void save_id(){
        DefaultTableModel mod = (DefaultTableModel)transaction.getModel();
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="update items set idname = ? where name = '"+name_ft.getSelectedItem().toString()+"'and iditems = '"+mod.getValueAt(0, 0)+"';";
        String sql2 ="select * from pharmacy_purchase where name = '"+name_ft.getSelectedItem().toString()+"';";
        
        
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql2);
            PreparedStatement ps = con.prepareStatement(sql) ;
            ps.setInt(1,rs.getInt("id") );
            
            ps.execute();
            
            
            
            
            System.out.print("save id done");
        }catch(SQLException ex){
            
        }
    }
    
    public void save_trans(){
        
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="insert into transaction( emp, cname, cphone, date, time ) values(?,?,?,?,?);";
        
        DefaultTableModel mod = (DefaultTableModel)items.getModel();
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            PreparedStatement ps = con.prepareStatement(sql) ;
            
            String emp_name = "null" ;
            if(cmp_emp.getSelectedItem() == "add new employee"){
                emp_name = new_emp.getText();
            }
            else {
                emp_name = cmp_emp.getSelectedItem().toString();
            }
            
            ps.setString(1, emp_name);
            ps.setString(2, cname.getText());
            ps.setString(3, cphone.getText());
            ps.setString(4, dt.getText());
            ps.setString(5, tm.getText());
            
            ps.execute();
            
            mod.setRowCount(0);
            load_trans();
            
            //System.out.print("save done");
        }catch(SQLException ex){
            
        }
    }
    
    public void delete() {
        DefaultTableModel mod = (DefaultTableModel)items.getModel();
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="delete from items where name = ? and iditems = ? ;";
        String update = "update pharmacy_purchase set qty = qty + '"+mod.getValueAt(items.getSelectedRow(), 1)+"' where name = '"+mod.getValueAt(items.getSelectedRow(), 0)+"' ;";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            
            DefaultTableModel mod1 = (DefaultTableModel)transaction.getModel();
            
            PreparedStatement  pst = con.prepareStatement(sql);
            
            pst.setString(1,mod.getValueAt(items.getSelectedRow(), 0).toString());
            pst.setInt(2, Integer.parseInt(mod1.getValueAt(0, 0).toString()));
            
            pst.execute();
            
            st.execute(update);
            mod.setRowCount(0);
            
            load_items();
            
        }catch(SQLException ex){
            
        }       
    
    }
    
    
    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeMouseEntered

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        // TODO add your handling code here:
       

    }//GEN-LAST:event_minMouseEntered

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        

    }//GEN-LAST:event_homeMouseEntered

    private void min1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseEntered
        // TODO add your handling code here:
        min.setVisible(true);
    }//GEN-LAST:event_min1MouseEntered

    private void close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseEntered
        // TODO add your handling code here:
        close.setVisible(true);
    }//GEN-LAST:event_close1MouseEntered

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        // TODO add your handling code here:
        home.setVisible(true);
    }//GEN-LAST:event_home1MouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        min.setVisible(false);
    }//GEN-LAST:event_minMouseExited

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setVisible(false);
    }//GEN-LAST:event_closeMouseExited

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setVisible(false);
    }//GEN-LAST:event_homeMouseExited

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void new_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_empActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_new_empActionPerformed

    private void name_ftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_ftActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_name_ftActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void cphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cphoneActionPerformed

    private void cmp_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp_empActionPerformed
        // TODO add your handling code here:
        if (cmp_emp.getSelectedItem() == "add new employee"){
            
            new_emp.setVisible(true);
            
        }
        else{
            new_emp.setVisible(false);
        }
        
    }//GEN-LAST:event_cmp_empActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        sell.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        done.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        delete.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
        add.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseEntered

    private void sellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellMouseExited
        // TODO add your handling code here:
        sell.setVisible(false);
    }//GEN-LAST:event_sellMouseExited

    private void doneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseExited
        // TODO add your handling code here:
        done.setVisible(false);
    }//GEN-LAST:event_doneMouseExited

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setVisible(false);
    }//GEN-LAST:event_deleteMouseExited

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setVisible(false);
    }//GEN-LAST:event_addMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(pharmacy_sell.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new main().setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        save_items();
        save_id();
        
    }//GEN-LAST:event_addMouseClicked

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        name_ft.removeAllItems();
        cmp_name_loading();
        
    }//GEN-LAST:event_nameKeyReleased

    private void quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyReleased
        // TODO add your handling code here:
        String url ="jdbc:mysql://localhost:3306/Project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="select * from pharmacy_purchase where name = '"+ name_ft.getSelectedItem().toString() +"';";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel mod = (DefaultTableModel)items.getModel();
            
            while(rs.next()){
                
                Double total_price = Integer.parseInt(quantity.getText()) *  rs.getDouble("price") ;
                
                
                
                price.setText(total_price.toString());
                
            }
            
            
            
            
            
        }
        catch(SQLException ex){
            
        }
    }//GEN-LAST:event_quantityKeyReleased

    private void doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseClicked
        // TODO add your handling code here:
        save_trans();
        
        
    }//GEN-LAST:event_doneMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_deleteMouseClicked

    private void sellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellMouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel)transaction.getModel();
        DefaultTableModel mod2 = (DefaultTableModel)items.getModel();
        
        mod.setRowCount(0);
        mod2.setRowCount(0);
        quantity.setText("");
        name.setText("");
        cname.setText("");
        cphone.setText("");
    }//GEN-LAST:event_sellMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacy_sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacy_sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacy_sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacy_sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pharmacy_sell().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(pharmacy_sell.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JComboBox<String> cmp_emp;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cphone;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel done;
    private javax.swing.JTextField dt;
    private javax.swing.JLabel home;
    private javax.swing.JLabel home1;
    private javax.swing.JTable items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> name_ft;
    private javax.swing.JTextField new_emp;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JScrollPane sc;
    private javax.swing.JScrollPane sc1;
    private javax.swing.JLabel sell;
    private javax.swing.JTextField tm;
    private javax.swing.JTable transaction;
    // End of variables declaration//GEN-END:variables
}
