/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form pharmacy
     */
    public pharmacy() {
        initComponents();
        load();
        
        close.setVisible(false);
        min.setVisible(false);
        home.setVisible(false);
        add.setVisible(false);
        delete.setVisible(false);
        update.setVisible(false);
        name.setBackground(new Color (255,255,255,50));
        price_p.setBackground(new Color (255,255,255,50));
        qty.setBackground(new Color (255,255,255,50));
        price.setBackground(new Color (255,255,255,50));
        num_of_bars.setBackground(new Color (255,255,255,50));
        
        
        ph_table.getColumnModel().getColumn(0).setMinWidth(0);
        ph_table.getColumnModel().getColumn(0).setMaxWidth(0);
        
        
        ph_table.setOpaque(false);
        sc.setOpaque(false);
        sc.getViewport().setOpaque(false);
        
        DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
        
        
        cr.setForeground(new Color (255, 51, 204));
        cr.setOpaque(false);
        
                
        
        for(int i = 0 ; i < 7 ; i++){
            
            ph_table.getColumnModel().getColumn(i).setCellRenderer(cr);
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        close2 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        min2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        home2 = new javax.swing.JLabel();
        sc = new javax.swing.JScrollPane();
        ph_table = new javax.swing.JTable();
        add = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        price_p = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        num_of_bars = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        for_ = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_ph.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 30, 40));

        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_ph2.png"))); // NOI18N
        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close2MouseExited(evt);
            }
        });
        getContentPane().add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, 40));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min_ph.png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 30, 50));

        min2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min_ph2.png"))); // NOI18N
        min2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min2MouseExited(evt);
            }
        });
        getContentPane().add(min2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 30, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_ph2.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_ph.png"))); // NOI18N
        home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home2MouseExited(evt);
            }
        });
        getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        ph_table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ph_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "for..", "price per bar", "price ", "number of bars", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ph_table.setRowHeight(30);
        ph_table.setRowMargin(3);
        ph_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph_tableMouseClicked(evt);
            }
        });
        sc.setViewportView(ph_table);

        getContentPane().add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 391, 1000, 310));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-50 (1).png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-50.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 50, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("update");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 80, 30));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-50 (3).png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 50, 50));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-50 (3).png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 80, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-50 (2).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 60, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-50 (2).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 60, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setText("delete");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("add");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 336, 50, 40));

        price_p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price_p.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(price_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 130, 40));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 204));
        jLabel8.setText("price per bar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 190, 40));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, 40));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 204));
        jLabel9.setText("price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 90, 40));

        num_of_bars.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        num_of_bars.setForeground(new java.awt.Color(255, 255, 255));
        num_of_bars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_of_barsActionPerformed(evt);
            }
        });
        getContentPane().add(num_of_bars, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 40));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 204));
        jLabel10.setText("number of bars");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 200, 40));

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 40));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 204));
        jLabel11.setText("name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 40));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 204));
        jLabel12.setText("for");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, 40));

        for_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        for_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eyes", "Bones", "Ear, Nose and Throat", "stomach", "Dental", "Neurologists", "Kindey", "Venereal" }));
        getContentPane().add(for_, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 140, 40));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 204));
        jLabel13.setText("Qantity");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 40));

        qty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qty.setForeground(new java.awt.Color(255, 255, 255));
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public static void load(){

        String url ="jdbc:mysql://localhost:3306/Project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="select * from pharmacy_purchase;";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            DefaultTableModel mod = (DefaultTableModel)ph_table.getModel();
            
            while(rs.next()){
                
                mod.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getString("for_"),rs.getDouble("price_per_bar"),rs.getDouble("price"),rs.getInt("num_of_bar"),rs.getInt("qty")});
                
            }
            
            System.out.print("load done");
            
            
            
        }
        catch(SQLException ex){
            
        }
    }
    
    public void save(){
        
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="insert into pharmacy_purchase( name, for_, price_per_bar, price, num_of_bar, qty) values(?,?,?,?,?,?);";
        
        DefaultTableModel mod = (DefaultTableModel)ph_table.getModel();
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            PreparedStatement ps = con.prepareStatement(sql) ;
            ps.setString(1, name.getText());
            ps.setString(2, for_.getSelectedItem().toString());
            ps.setDouble(3, Double.parseDouble(price_p.getText()));
            ps.setDouble(4, Double.parseDouble(price.getText()));
            ps.setInt(5, Integer.parseInt(num_of_bars.getText()));
            ps.setInt(6, Integer.parseInt(qty.getText()));
            
            ps.execute();
            
            mod.setRowCount(0);
            load();
            
            System.out.print("save done");
        }catch(SQLException ex){
            
        }
    }
    
    public void delete(){
    
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="delete from pharmacy_purchase where id = ? ;";
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            DefaultTableModel mod = (DefaultTableModel)ph_table.getModel();
            
            PreparedStatement  pst = con.prepareStatement(sql);
            
            pst.setInt(1,(Integer.parseInt( mod.getValueAt(ph_table.getSelectedRow(), 0).toString())));
            
            pst.execute();
            
            mod.setRowCount(0);
            
            load();
            
        }catch(SQLException ex){
            
        } 
    
    }
    
    public void update(){
        
        String url ="jdbc:mysql://localhost:3306/project0" ;
        String user ="root";
        String pass ="Alora@19/7$";
        String sql ="update pharmacy_purchase set name = ? ,  for_ = ? ,  price_per_bar = ? , price = ? , num_of_bar = ? , qty = ? where id = ? ;";
        
        DefaultTableModel mod = (DefaultTableModel)ph_table.getModel();
        
        try(Connection con = DriverManager.getConnection(url, user, pass)){
            
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, name.getText());
            pst.setString(2, for_.getSelectedItem().toString());
            pst.setDouble(3, Double.parseDouble(price_p.getText()));
            pst.setDouble(4, Double.parseDouble(price.getText()));
            pst.setInt(5, Integer.parseInt(num_of_bars.getText()));
            pst.setInt(6, Integer.parseInt(qty.getText()));
            pst.setInt(7, Integer.parseInt(mod.getValueAt(ph_table.getSelectedRow(), 0).toString()));
            pst.execute();
            
            mod.setRowCount(0);
            
            load();
            
        }catch(SQLException ex){
            
        }
        
    }
        
    
    
    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        min.setVisible(false);
    }//GEN-LAST:event_minMouseExited

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_minMouseEntered

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homeMouseEntered

    private void close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_close2MouseExited

    private void min2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_min2MouseExited

    private void home2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_home2MouseExited

    private void close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseEntered
        // TODO add your handling code here:
        close.setVisible(true);
    }//GEN-LAST:event_close2MouseEntered

    private void min2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseEntered
        // TODO add your handling code here:
        min.setVisible(true);
    }//GEN-LAST:event_min2MouseEntered

    private void home2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseEntered
        // TODO add your handling code here:
        home.setVisible(true);
    }//GEN-LAST:event_home2MouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setVisible(false);
    }//GEN-LAST:event_closeMouseExited

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setVisible(false);
    }//GEN-LAST:event_homeMouseExited

    private void close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_close2MouseClicked

    private void min2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseClicked
        // TODO add your handling code here:
        this.setState(pharmacy.ICONIFIED);
    }//GEN-LAST:event_min2MouseClicked

    private void home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_home2MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(pharmacy.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        add.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        delete.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        update.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setVisible(false);
    }//GEN-LAST:event_addMouseExited

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setVisible(false);
    }//GEN-LAST:event_deleteMouseExited

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        update.setVisible(false);
    }//GEN-LAST:event_updateMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_addMouseClicked

    private void num_of_barsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_of_barsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_of_barsActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        save();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_deleteMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_updateMouseClicked

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ph_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph_tableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel mod = (DefaultTableModel)ph_table.getModel();
        
        name.setText(mod.getValueAt(ph_table.getSelectedRow(), 1).toString());
        for_.setSelectedItem(mod.getValueAt(ph_table.getSelectedRow(), 2).toString());
        price_p.setText(mod.getValueAt(ph_table.getSelectedRow(), 3).toString());
        price.setText(mod.getValueAt(ph_table.getSelectedRow(), 4).toString());
        num_of_bars.setText(mod.getValueAt(ph_table.getSelectedRow(), 5).toString());
        qty.setText(mod.getValueAt(ph_table.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_ph_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close2;
    private javax.swing.JLabel delete;
    private javax.swing.JComboBox<String> for_;
    private javax.swing.JLabel home;
    private javax.swing.JLabel home2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num_of_bars;
    public static javax.swing.JTable ph_table;
    private javax.swing.JTextField price;
    private javax.swing.JTextField price_p;
    private javax.swing.JTextField qty;
    private javax.swing.JScrollPane sc;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
